class ShieldIos < Formula
  include Language::Python::Virtualenv

  desc "iOS application protection: obfuscation, encryption, and runtime security"
  homepage "https://www.bytehide.com"
  url "https://files.pythonhosted.org/packages/source/b/bytehide-shield-ios/bytehide_shield_ios-0.1.0.tar.gz"
  sha256 "PLACEHOLDER"
  license :cannot_represent

  depends_on "python@3.12"

  # Resources are auto-generated by the update-homebrew workflow.
  # To regenerate manually: pip install homebrew-pypi-poet && poet bytehide-shield-ios

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "shield-ios", shell_output("#{bin}/shield-ios --help")
  end
end
